### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by XhmikosR**
Add Tests badge

### CODE REVIEW

**Comment by XhmikosR** [comment]
I can't make the badge to work

**Comment by paulmillr** [comment]
How do you think it'll be useful? I'm not a big fan of including too many s inside readmes, because every foreign host means one more tracker. We can see the build status already from this page: https://github.com/paulmillr/readdirp/commits/master

**Comment by XhmikosR** [comment]
It's your call. I personally just find it useful to quickly go to the build status from the README.

That being said, you now use GitHub Actions, I don't think there's an extra tracker :P

**Comment by XhmikosR** [comment]
@paulmillr can you decide about this and the other open PR and then release a new version? If I knew you'd release a new chokidar version I'd ping you sooner so that we include the new readdirp version there too.

**Pull request closed without merging**
