### PR TITLE
Fix #138 (dir entries getting droped due to race condition)

### LINKED ISSUE #138: Inconsistent results when running same test repeatedly(?!?)
[Environment: MacOSX Mojave, node v12.10.0, readdirp 3.2.0]

Running `readdirp()` periodically, exact same code, exact same directory... and I get different output. :-(

Here's the recipe:
```
# Start in a clean directory, install readdirp
mkdir temp && cd temp && npm i readdirp
 
# Create a directory with a few subdirectories
mkdir -p foo/bar/a foo/bar/b foo/blarg/a foo/blarg/b

# Create a test that scans the directory once/second
cat > test.js << EOT
const readdirp = require('readdirp');

setInterval(async function() {
  const results = await readdirp.promise('foo', {type: 'directories', depth: 1})
  console.log(results.map(r => r.path));
}, 1000);
EOT

# Run test.  Notice results are not consistent (!!!)
node test.js
```
Here's what I see in the console ...
```
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
[ 'bar', 'blarg' ]
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
[ 'bar', 'blarg' ]
[ 'bar', 'blarg' ]
[ 'bar', 'blarg', 'blarg/a', 'blarg/b' ]
... etc
```
Possibly related to #91?

### PR DESCRIPTION
**Pull request by broofa**
Okay, so ignore my previous description - there's a bit more here than I had initially.

First, I've removed the `setImmediate()` call to fix the issue I reported in #138.  However this re-broke the asyncIterator behavior.  I'm pretty sure the problem there was in the `_read()` implementation, which was ignoring the return value of `push()`.  [Per the Node docs](https://nodejs.org/api/stream.html#stream_readable_read_size_1), when `_read()` is called you're supposed to `push()` data until `push()` returns false, then wait for _read() to be called again.    Because the code was blindly `push()`ing with no regard for the return value,  I think that caused the stream to drop out of "flowing" mode,  effectively hanging the async iterator.  (Admittedly, this at the limit of my understanding of how streams work, so I may not have that exactly right, but I that's my best guess at the issue.  Also, I'm not sure how to explain the various tests people reported, mine included, just cleanly exiting rather than hanging. :-/ )

I'm pretty sure this misbehaving `_read()` is what was causing #91 and #97.

To fix this, I rewrote `_read()` to have a while-true loop that does two thngs: 1) "explore" the filesystem until it gets some entries to push, and 2) push() entries until it sees `false`.  It only drops out of that loop when `push() == false` (or we run out of things to explore).

Other changes of note:
- Use Promise.all to parallelize getting dirent stats
- Use `_reading` mutex in _read rather than the more complicated `filesToRead` logic.
- _exploreDirectory() returns entries to main _read loop, rather than pushing them.
- added check in readdirp#promise's 'error' event handler so errors after promise resolves won't be silently swallowed.
- Removed the "missing file" test.  I think that test relied on the fact that exploring of the directory was deferred until after the "readable" event fired (due to the setImmediate() call).  But that's no longer the case in this PR - the directory is pushed before "readable" fires now.... and I don't really see how to replicate that test easily.
- Remove `highWaterMark` option - it's just a hint passed into `_read()`, which is ignored anyhow.

### CODE REVIEW

**Comment by paulmillr** [comment]
Can you measure RAM and CPU impact of your changes? Pick a directory with 100,000 files and more for this.

**Comment by broofa** [comment]
Added "examples/perf.js", which basically does the same thing as "examples/list.js", but logs `process.memoryUsage()` info every 500ms.  Here's what I get when running 3x with this PR:
```
$ node perf.js
 37000 rss=44.2M   heapTotal=25.8M   heapUsed=7.4M    external=0.7M
 78000 rss=45.0M   heapTotal=26.2M   heapUsed=13.7M   external=0.8M
124000 rss=45.6M   heapTotal=26.2M   heapUsed=9.3M    external=0.8M
165000 rss=45.6M   heapTotal=26.2M   heapUsed=11.7M   external=0.8M
194467 rss=62.8M   heapTotal=43.2M   heapUsed=20.1M   external=0.8M
Processed 194467 files in 2357 msecs

$ node perf.js
 37000 rss=44.2M   heapTotal=25.0M   heapUsed=8.1M    external=0.7M
 84000 rss=45.3M   heapTotal=26.2M   heapUsed=10.2M   external=0.8M
130000 rss=45.5M   heapTotal=26.2M   heapUsed=12.0M   external=0.8M
171000 rss=45.6M   heapTotal=26.2M   heapUsed=8.4M    external=0.8M
194467 rss=45.7M   heapTotal=26.2M   heapUsed=12.9M   external=0.8M
Processed 194467 files in 2341 msecs

$ node perf.js
 34000 rss=43.7M   heapTotal=25.0M   heapUsed=12.4M   external=0.7M
 82000 rss=44.5M   heapTotal=25.4M   heapUsed=11.4M   external=0.8M
128000 rss=45.0M   heapTotal=25.9M   heapUsed=10.6M   external=0.8M
166000 rss=45.0M   heapTotal=25.9M   heapUsed=8.2M    external=0.8M
194467 rss=45.2M   heapTotal=25.9M   heapUsed=11.8M   external=0.8M
Processed 194467 files in 2340 msecs
```
And here's what I get with that same test, running against the current `master`:
```
$ node perf.js
 29000 rss=78.1M   heapTotal=50.9M   heapUsed=26.1M   external=0.7M
 97000 rss=87.4M   heapTotal=58.5M   heapUsed=17.5M   external=0.8M
176000 rss=97.6M   heapTotal=69.0M   heapUsed=46.6M   external=0.8M
194467 rss=103.2M  heapTotal=74.3M   heapUsed=41.0M   external=0.8M
Processed 194467 files in 1706 msecs

$ node perf.js
 33000 rss=80.7M   heapTotal=53.8M   heapUsed=28.4M   external=0.7M
108000 rss=84.9M   heapTotal=55.9M   heapUsed=24.4M   external=0.8M
185000 rss=102.0M  heapTotal=73.7M   heapUsed=44.2M   external=0.8M
194467 rss=104.2M  heapTotal=75.3M   heapUsed=54.6M   external=0.8M
Processed 194467 files in 1613 msecs

$ node perf.js
 20000 rss=71.0M   heapTotal=46.7M   heapUsed=21.4M   external=0.7M
 74000 rss=97.4M   heapTotal=69.3M   heapUsed=40.0M   external=0.8M
143000 rss=89.3M   heapTotal=60.6M   heapUsed=28.8M   external=0.8M
194467 rss=102.2M  heapTotal=73.5M   heapUsed=45.7M   external=0.8M
Processed 194467 files in 1929 msecs
```
So... looks like this PR is more memory efficient, but slightly less performant.

**Comment by paulmillr** [comment]
@ronag what are your thoughts on that?

**Comment by ronag** [comment]
> when _read() is called you're supposed to push() data until push() returns false, then wait for _read() to be called again. Because the code was blindly push()ing with no regard for the return value, I think that caused the stream to drop out of "flowing" mode, effectively hanging the async iterator.

I don't think this is correct. You should stop pushing if it it returns false, but it's just a hint. Also you can just push once and then _read will be called again.

What is the actual problem here?

**Comment by ronag** [comment]
Ah, didn't see the referred issues. That's going to take some time to dig into.

**Comment by paulmillr** [comment]
@ronag the main issue here was https://github.com/paulmillr/readdirp/issues/138: while using `setInterval`, readdirp was giving different results sometimes.

**Comment by broofa** [comment]
@paulmillr @ronag To clarify, the issue isn't the use of setInterval, per se.  The issue is the race condition that arises from push()'ing to the Readable stream asynchronously (and ignoring the return value of push()).  But, because it's a race condition, the issue manifests sporadically.  So demonstrating the problem requires running multiple times until the behavior manifests.  At least, on my laptop it does.

**Pull request closed without merging**
