### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
* dtslint 1.0.2
* picomatch 2.1.0

### CODE REVIEW

**Comment by paulmillr** [comment]
Why update stuff like picomatch if it'll use 2.1.0 already? I suggest to only update those if we *need* the update. Otherwise npm would not be able to flatten similar versions to one.

**Comment by XhmikosR** [comment]
This makes sure consumers of the package will get 2.1.0. Otherwise they might not get the latest.

**Comment by XhmikosR** [comment]
If you want, you can bump everything before a release. Not sure when you plan to make one.

**Comment by paulmillr** [comment]
> Otherwise they might not get the latest

We don't care about that. It's not an important package. I mean, the 2.1.0 update is not too important. Otherwise i'd ensure it's the latest.

> flattening: if one is using semver ranges, this will be properly flattened too

Not if some software uses ~2.0.7 and ours using ^ 2.0.7 — the current way would keep it 2.0.7 and we don't care about that.

**Comment by paulmillr** [comment]
Updating dtslint is good though

**Comment by XhmikosR** [comment]
I still think 2.1.0 is a good candidate, but it's your call ultimately. I also submitted a few PRs upstream, not sure if they will be accepted, but removes a few redundant stuff.

**Pull request closed without merging**
