### PR TITLE
simplify and fix race condition

### PR DESCRIPTION
**Pull request by ronag**
Tries to address:

 - https://github.com/paulmillr/readdirp/issues/138
 - https://github.com/paulmillr/readdirp/pull/139

It's easier to just look at `_read` than the diff.

### CODE REVIEW

**Comment by broofa** [comment]
Pulled this locally and ran the example I provided in #138 and it works. (Yay!)  As does `examples/list.js`.

What happens if `push()` returns false before the [`_read()` for-loop](https://github.com/paulmillr/readdirp/blob/895bcf879ce82f5c2456d63e4a44ed77cedb9c18/index.js#L140) completes?  The for-loop continues until all `promises` have been processed (i.e. pushed), regardless, which would seem to be in direct conflict with [the expected behavior](https://nodejs.org/api/stream.html#stream_readable_read_size_1):

> _read() should continue reading from the resource and pushing data until readable.push() returns false. Only when _read() is called again after it has stopped should it resume pushing additional data onto the queue.

Is this going to cause problems?  (I'm not a streams guru, but my reading of the source has me thinking Readable still adds the chunk, as expected.  It just won't call read() again until it's internal buffer of chunks is falls back below the highwater mark.  Is that right?)

**Comment by ronag** [comment]
> Is this going to cause problems? 

No, it will just buffer the chunks. The return value is just a hint.

> (I'm not a streams guru, but my reading of the Readable source in node.js has me thinking it will buffer chunks, even if the buffer is above the highwater mark. It just won't call read() again until it's internal buffer of chunks is falls back below the highwater mark. Is that right?)

Correct.

**Comment by paulmillr** [comment]
Why did you remove highwatermark: 1? This breaks ENOENT test consistently. Or, our test is written in an invalid way?

**Comment by ronag** [comment]
> Why did you remove highwatermark: 1? This breaks ENOENT test consistently. Or, our test is written in an invalid way?

Performance reasons. It will stop buffering after a single element.

Which test breaks?

**Comment by ronag** [comment]
`should emit warning for missing file`?

**Comment by ronag** [comment]
Yes, not sure how I missed that. Probably some last minute change. Apologies. I'll sort it out ASAP.

**Comment by ronag** [comment]
I don't understand this test. What is it supposed to test?

**Comment by paulmillr** [comment]
Consider a situation:

1. readdirp() is initialized on some big root directory
2. readdirp() receives path a/b/c to its queue
3. readdirp is reading something else
4. a/b gets deleted, so stat()-ting a/b/c would now emit enoent
5. We should emit warnings for this case.

**Comment by ronag** [comment]
Ok. I undestand. I don't think the test is correctly written. We need x > highWaterMark number of entries and then delete an entry which is above that number in the sequence.

**Comment by ronag** [comment]
Ah, I can see you already fixed it. Anyway, here is a PR. https://github.com/paulmillr/readdirp/pull/141

**Pull request merged**
