### PR TITLE
Updates JSDoc params for readdir constructor

### PR DESCRIPTION
**Pull request by brandondc741**
**Documentation change**
Denotes callback as **optional** and adds an **Object** type in readdir JSDocs.

### CODE REVIEW

**Comment by brandondc741** [comment]
Because I hate seeing IDE's squiggly lines

**Comment by paulmillr** [comment]
There is no such code in master — Check out the merge conflicts.

**Comment by brandondc741** [comment]
You're right. This is supposed to be a change to **v2.x** , not **v3.x**. How would I resolve this?

**Comment by paulmillr** [comment]
Maybe we don’t merge it? V3 is coming soon, and it’s  the massive improvement over v2. It doesn’t make sense to release new v2 just for the comment change. Comment change AND something else could make sense

**Pull request closed without merging**
