### PR TITLE
dtslint updates

### PR DESCRIPTION
**Pull request by XhmikosR**
Instead run it once, only on Node.js 12 and on Ubuntu.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I'm thinking maybe we should move dtslint to a separate action?

**Comment by XhmikosR** [comment]
@paulmillr let me know what you prefer and I'll rebase this. I also renamed the matrix `node-version` to `node` since it's shorter.

**Comment by XhmikosR** [comment]
It's still just too slow... It's better than before since the other workflows finish on 1/4 of the time.

But dtslint still has to download all the types for all versions (also has 92 dependencies). Maybe there's a way to tweak its behavior? I'm not familiar with dtslint at all myself. Or maybe there's another package we should use.

Either way, when we have caching on Actions, this won't be a problem for subsequent runs.

**Comment by paulmillr** [comment]
Let’s reduce the amount of versions it downloads to maybe 4 most recent.

**Comment by XhmikosR** [comment]
I'm not sure how to do that :P

**Comment by XhmikosR** [comment]
I think it still makes sense to have dtslint as a separate action. When we have caching in actions, we can cache dtslint download folder and this will be a lot faster, hopefully.

**Comment by XhmikosR** [comment]
I'll do the same for chokidar, if this lands.

**Comment by paulmillr** [comment]
prob a good idea to make this a sub-job of `lint` category? similar to eslint

**Comment by XhmikosR** [comment]
I can move eslint and dtslint to a "Lint" action, if you prefer that. And only run it for Node.js 12

**Comment by XhmikosR** [comment]
Pushed. Do note that there's a limit in concurrent actions (I think it's 16)

**Comment by XhmikosR** [comment]
I think the previous solution was faster.

**Pull request merged**
