### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by southpolesteve**
Removes example and test code from distributed npm package

### CODE REVIEW

**Comment by thlorenz** [comment]
Not interested .. none of these are huge and including them with the install helps you understand how things work .. i.e. if you're somewhere without internet and are working with it.

If you can convince me otherwise, i.e. what is the big deal of including this I'm open to change my mind ;)

**Comment by southpolesteve** [comment]
My personal reason behind this is that AWS Lambda deployments have a hard limit of 250mb and soft limit of 10mb when using their API. If you go over 10mb you need an extra step involving S3. I've hit both these limits on projects. One quick fix has been to get rid of extra stuff in `node_modules`. Lots of small modules === lots of small extra files. I've been pushing those changes upstream when it seems to make sense.

Obviously your repo, so your call, just wanted you to know my motivation. Thanks for making this module in the first place and also for looking at this PR!

**Comment by thlorenz** [comment]
OK gotcha .. unfortunately some test(s) are currently failing .. not your fault they have been before.
Could you maybe help me figure out why and fix it here so we can merge your PR and have all tests pass as a result as well?

I'd totally appreciate that but understand if you pass due to time constraints.

**Comment by yoshuawuyts** [comment]
I refer to docs offline all the time, removing them would definitely come back to bite me. If AWS lambda has hard caps, it should probably be resolved on their end. This would literally just remove a couple of KB; I think there's bigger gains to be made elsewhere (e.g. are you using `babel` or `electron`? Those deps are massive, consider removing those first).

**Comment by thlorenz** [comment]
@yoshuawuyts this is just about removing tests and examples, not the Readme.
However I agree that the code in there is not big.

**Comment by yoshuawuyts** [comment]
@thlorenz ran into this yesterday even with [`tcomb`](https://github.com/gcanti/tcomb) - they strip their `docs/` and `tests/` from the npm output, had to wait a couple of hours before I could continue. Having access to either would've probably helped a great deal, as their readme didn't cover all cases.

There's been prior discussion about this topic on https://github.com/substack/tape/pull/260.

**Comment by thlorenz** [comment]
@southpolesteve Please show that this makes a meaningful difference, i.e. only if the tarball is significantly smaller will I consider the pull, otherwise not since for some people working offline it is important to access the tests as part of the packages they installed locally on their machine.

You can compare the sizes as follows:

```sh
git checkout master
npm pack
du -h *.tgz

git checkout <your-branch>
npm pack
du -h *.tgz
```

**Comment by doug-wade** [comment]
fwiw, I measure a 33% reduction in the tarball size

```
dougwade code/readdirp ‹reduce-package-size› » npm pack
du -h *.tgz
(node:47721) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
readdirp-2.0.1.tgz
dougwade code/readdirp ‹reduce-package-size*› » du -h *.tgz
12K	readdirp-2.0.1.tgz
dougwade code/readdirp ‹reduce-package-size*› » vim .npmignore
dougwade code/readdirp ‹reduce-package-size*› » rm readdirp-2.0.1.tgz
dougwade code/readdirp ‹reduce-package-size*› » npm pack
(node:47841) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
readdirp-2.0.1.tgz
dougwade code/readdirp ‹reduce-package-size*› » du -h *.tgz
8.0K	readdirp-2.0.1.tgz
```

33% is a lot of %, but 4K is not a lot of K, so ¯\_(ツ)_/¯

**Comment by thlorenz** [comment]
@doug-wade that's quite substantial even if we're just talking 4K.
Could you do me a favor and LMK how much we'd win by only removing examples?
I'd really like to keep the tests in.

**Comment by paulmillr** [comment]
Resolved, see #55

**Pull request closed without merging**
