### PR TITLE
Support symlink on directories

### PR DESCRIPTION
**Pull request by znarf**
Fix https://github.com/paulmillr/readdirp/issues/150

### CODE REVIEW

**Comment by paulmillr** [comment]
We absolutely can’t use synchronous fs methods. They block event loop.

**Comment by paulmillr** [comment]
Ensure you add tests to the feature. Tests must fail before your commits and pass after.

**Comment by znarf** [comment]
@paullmilr

> We absolutely can’t use synchronous fs methods. They block event loop.

Would you be fine if I refactor these parts using async/await ?

**Comment by paulmillr** [comment]
Sure. 

Also, ensure the performance isn’t degrading by 50% or so. The library is used by millions of folks.

For example, the behavior should probably only be used for followSymlinks option

**Comment by znarf** [comment]
> Also, ensure the performance isn’t degrading by 50% or so.

Do you have a benchmark to recommend?

> For example, the behavior should probably only be used for followSymlinks option

Do you mean `lstat: true`? Or should we introduce a more explicit `followSymlinks` option?

Note: it's actually currently unclear to me what is the excact purpose of `lstat: true`, because `symlinks` are returned just fine without it.

**Comment by paulmillr** [comment]
node examples/bench.js

Try your case with lstat: true and see what happens.

**Comment by znarf** [comment]
> node examples/bench.js

Cool, no regression but more files are being returned. Makes sense, because the symlinked directories are now followed.

> Try your case with `{lstat: true}` and see what happens.

I tried and haven't seen a difference regarding symlinks. In the test suite (old test and new test), the symlinks are properly followed without setting this option. Maybe a relic of the past?

If you don't want the symlinks to be followed, I suggest to add an explicit `followSymlinks` as a boolean. Should I do that, default to `true`?

Except that, the PR is ready for review, refactored using async/await and added a test.

**Comment by znarf** [comment]
@paulmillr what do you think? could you review so we can move forward with that?

Some context about this change: I'm proposing to integrate `readdirp` in a nice other open source project and this issue is currently a blocker, ref https://github.com/depcheck/depcheck/pull/498

**Comment by paulmillr** [comment]
@znarf I will test this on my machine(s) and merge ASAP. Overall, looks good!

**Comment by znarf** [comment]
Any luck? :-)

**Comment by paulmillr** [comment]
Merged. Thank you. Required an adjustment to fix error when the result path doesn't exist.

**Comment by znarf** [comment]
@paulmillr Excellent! Thank you.

**Pull request merged**
